---
- hosts: dellos10
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "enable ports"
    dellos10_config:
      lines:
        - no shutdown
      parents: ['interface ethernet{{ item }}']
    with_items: "{{ PORTS }}"
      









